name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '.github/scripts/**'
      - '.github/workflows/build_push.yml'
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 65
  IS_PR_CHECK: false

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      latestCommitMessage: ${{ steps.set-env.outputs.LATEST_COMMIT_MESSAGE }}
      matrix: ${{ steps.generate-matrices.outputs.matrix }}
      delete: ${{ steps.generate-matrices.outputs.delete }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set env
        id: set-env
        run: |
          echo "LATEST_COMMIT_MESSAGE<<{delimiter}
          $(git log -1 --pretty=%B)
          {delimiter}" >> $GITHUB_OUTPUT

      - id: generate-matrices
        name: Create output matrices
        run: |
          python ./.github/scripts/generate-build-matrices.py "HEAD~1" Release

  build:
    name: Build extensions (${{ matrix.chunk.number }})
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ toJson(fromJson(needs.prepare.outputs.matrix).chunk) != '[]' }}
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ matrix.chunk.number > 1 }}

      - name: Prepare signing key
        if: ${{ env.SIGNING_KEY != '' }}
        run: |
          echo "$SIGNING_KEY" | base64 -d > signingkey.jks

      - name: Build extensions (${{ matrix.chunk.number }})
        env:
          MODULES: ${{ join(matrix.chunk.modules, ' ') }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew $MODULES

      - name: Upload APKs (${{ matrix.chunk.number }})
        uses: actions/upload-artifact@v4
        with:
          name: "individual-apks-${{ matrix.chunk.number }}"
          path: "**/*.apk"
          retention-days: 1

      - name: Clean up CI files
        if: always()
        run: rm -f signingkey.jks

  publish:
    name: Publish extension repo
    needs: [prepare, build]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          path: ~/apk-artifacts

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create repo artifacts
        run: |
          python ./.github/scripts/move-built-apks.py
          
          # Use Keiyoushi inspector
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/keiyoushi/extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          
          # The move-built-apks.py script already creates a 'repo' folder
          java -jar ./Inspector.jar "repo/apk" "output.json" "tmp"
          
          # Create index
          python ./.github/scripts/create-repo.py

      - name: Deploy to repo branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: repo
          folder: repo
          clean: true
          commit-message: "Update extension repo: ${{ needs.prepare.outputs.latestCommitMessage }}"
